export const MOVIE_FETCH = "movie/FETCH";
export const MOVIE_FETCH_SUCCESS = "movie/FETCH_SUCCESS";
export const MOVIE_FETCH_FAILURE = "movie/FETCH_FAILURE";

export const MOVIE_DETAIL_FETCH = "movie/DETAIL_FETCH";
export const MOVIE_DETAIL_FETCH_SUCCESS = "movie/DETAIL_FETCH_SUCCESS";
export const MOVIE_DETAIL_FETCH_FAILURE = "movie/DETAIL_FETCH_FAILURE";